import type { CardItem } from "./types/card";

export const BASE_CARDS: CardItem[] = [
  {
    id: "0",
    title: "Card 0",
    description: "New card",
    x: 96,
    y: 70,
    rotate: -3,
  },
  {
    id: "1",
    title: "Card 1",
    description: "New card",
    x: 352,
    y: 70,
    rotate: 0,
  },
  {
    id: "2",
    title: "Card 2",
    description: "New card",
    x: 608,
    y: 70,
    rotate: 3,
  },
  {
    id: "3",
    title: "Card 3",
    description: "New card",
    x: 864,
    y: 70,
    rotate: -3,
  },
  {
    id: "4",
    title: "Card 4",
    description: "New card",
    x: 1024,
    y: 70,
    rotate: 0,
  },
  {
    id: "5",
    title: "Card 5",
    description: "New card",
    x: 96,
    y: 250,
    rotate: 3,
  },
  {
    id: "6",
    title: "Card 6",
    description: "New card",
    x: 352,
    y: 250,
    rotate: -3,
  },
  {
    id: "7",
    title: "Card 7",
    description: "New card",
    x: 608,
    y: 250,
    rotate: 0,
  },
  {
    id: "8",
    title: "Card 8",
    description: "New card",
    x: 864,
    y: 250,
    rotate: 3,
  },
  {
    id: "9",
    title: "Card 9",
    description: "New card",
    x: 1024,
    y: 250,
    rotate: -3,
  },
  {
    id: "10",
    title: "Card 10",
    description: "New card",
    x: 96,
    y: 430,
    rotate: 0,
  },
  {
    id: "11",
    title: "Card 11",
    description: "New card",
    x: 352,
    y: 430,
    rotate: 3,
  },
  {
    id: "12",
    title: "Card 12",
    description: "New card",
    x: 608,
    y: 430,
    rotate: -3,
  },
  {
    id: "13",
    title: "Card 13",
    description: "New card",
    x: 864,
    y: 430,
    rotate: 0,
  },
  {
    id: "14",
    title: "Card 14",
    description: "New card",
    x: 1024,
    y: 430,
    rotate: 3,
  },
  {
    id: "15",
    title: "Card 15",
    description: "New card",
    x: 96,
    y: 610,
    rotate: -3,
  },
  {
    id: "16",
    title: "Card 16",
    description: "New card",
    x: 352,
    y: 610,
    rotate: 0,
  },
];
